<?php 
// istanzio oggetti Movie

$movies = [
  new Movie("Guardians Of The Galaxy Vol. 3", ['Adventure', 'Action', 'Comedy'], "2h 30m", 8, "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own - a mission that could mean the end of the Guardians if not successful.", "./imgs/guardians3.jpg"),
  new Movie("John Wick: Chapter 4", ['Action', 'Crime', 'Thriller'], "2h 49m", 8, "Condemned by the tyrannical High Table to be on the run for the rest of his life, deadly assassin maestro John Wick (2014) embarks on a Sisyphean mission of suicidal fury to decide his fate after the merciless carnage in John Wick: Chapter 3 - Parabellum (2019).", "./imgs/johnWick4.jpg"),
  new Movie("Dungeons & Dragons - Honor Among Thieves", ['Action', 'Adventure', 'Comedy'], "2h 14m", 7.5, "A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people. Dungeons and Dragons: Honor Among Thieves brings the rich world and playful spirit of the legendary roleplaying game to the big screen in a hilarious and action-packed adventure.", "./imgs/dnd.jpg"),
  new Movie("The Super Mario Bros. Movie", ['Animation', 'Adventure', 'Comedy'], "1h 32m", 7.3, "A Brooklyn plumber named Mario travels through the Mushroom Kingdom with a princess named Peach and an anthropomorphic mushroom named Toad to find Mario's brother, Luigi, and to save the world from a ruthless fire-breathing Koopa named Bowser.", "./imgs/mario.jpg"),
  new Movie("Avatar: The Way of Water", ['Action', 'Adventure', 'Fantasy'], "3h 12m", 7.7, "Several years after the Na'vi repelled the RDA invasion Jake Sully and his family are living on Pandora. Things seem peaceful but the RDA has other plans, invading and capturing Pandora. Sully forms a guerrilla group to try to expel the invaders.", "./imgs/avatar.jpg"),
  new Movie("Interstellar", ['Adventure', 'Drama', 'Sci-Fi'], "2h 49m", 8.6, "Earth's future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind's survival: Interstellar travel. A newly discovered wormhole in the far reaches of our solar system allows a team of astronauts to go where no man has gone before, a planet that may have the right environment to sustain human life.", "./imgs/interstellar.jpg")
];
